---

- name: sysctl vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ sysctl_vfs_cache_pressure }}"
    state: present

- name: sysctl vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ sysctl_vm_swappiness }}"
    state: present

- name: sysctl vm.dirty_background_ratio
  sysctl:
    name: vm.dirty_background_ratio
    value: "{{ sysctl_vm_dirty_background_ratio }}"
    state: present

- name: sysctl vm.dirty_ratio
  sysctl:
    name: vm.dirty_ratio
    value: "{{ sysctl_vm_dirty_ratio }}"
    state: present
