---

- name: Create group
  group: name={{ consul_group }} state=present system=true

- name: Create user
  user: name={{ consul_user }} state=present group={{ consul_group }} system=true comment='System user for running Consul'

- name: Create folders
  file: path={{ item.path }} state=directory owner={{ item.owner }} group={{ item.group }} mode=0755
  with_items:
    - { path: "{{ consul_data_path }}", owner: "{{ consul_user }}", group: "{{ consul_group }}" }
    - { path: "{{ consul_config_path }}", owner: root, group: root }
    - { path: '/opt/src', owner: root, group: root }

- name: Download
  get_url: url={{ consul_package_url }} sha256sum={{ consul_package_checksum }} dest=/opt/src/{{ consul_package_name }}

- name: Unarchive
  unarchive: copy=no src=/opt/src/{{ consul_package_name }} dest={{ consul_install_path }} owner=root group=root mode=0755

- name: Configure
  template: src=00-defaults.json.j2 dest={{ consul_config_path }}/00-defaults.json
  notify:
    - restart consul
  tags: ["consul_conf"]

- name: systemd script
  template: src=consul.service.j2 dest=/usr/lib/systemd/system/consul.service
  notify:
    - reload systemd
    - restart consul

- name: install consul cli
  yum:
    name: "{{ consul_cli_package }}"
    state: present

- name: install scripts
  become: yes
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - consul-wait-for-leader.sh
    - consul-rolling-restart.sh
    - check-service-active

- name: enable consul service
  service: name=consul enabled=yes
