
module "az-d" {
  source = "./availability-zone"
  cluster_tag_name = "${var.cluster_tag_name}"
  ami = "${var.ami}"
  controller_server_count = "${var.controller_server_count}"
  edge_server_count = "${var.edge_server_count}"
  kafka_connect_server_count = "${var.kafka_connect_server_count}"
  kafka_connect_lsql_server_count = "${var.kafka_connect_lsql_server_count}"
  kafka_server_count = "${var.kafka_server_count}"
  kafka_zk_server_count = "${var.kafka_zk_server_count}"
  resource_server_count = "${var.resource_server_count}"
  vpn_server_count = "${var.vpn_server_count}"
  controller_server_instance_type = "${var.controller_server_instance_type}"
  edge_server_instance_type = "${var.edge_server_instance_type}"
  kafka_connect_server_instance_type = "${var.kafka_connect_server_instance_type}"
  kafka_connect_lsql_server_instance_type = "${var.kafka_connect_lsql_server_instance_type}"
  kafka_server_instance_type = "${var.kafka_server_instance_type}"
  kafka_zk_server_instance_type = "${var.kafka_zk_server_instance_type}"
  resource_server_instance_type = "${var.resource_server_instance_type}"
  vpn_server_instance_type = "${var.vpn_server_instance_type}"
  controller_server_ami = "${var.controller_server_ami}"
  edge_server_ami = "${var.edge_server_ami}"
  kafka_connect_server_ami = "${var.kafka_connect_server_ami}"
  kafka_server_ami = "${var.kafka_server_ami}"
  kafka_zk_server_ami = "${var.kafka_zk_server_ami}"
  resource_server_ami = "${var.resource_server_ami}"
  vpn_server_ami = "${var.vpn_server_ami}"
  vpc_id = "${aws_vpc.default.id}"
  gateway_id = "${aws_internet_gateway.default.id}"
  vpc_gateway_id = "${aws_vpn_gateway.vpn_gw.id}"
  default_security_group_id = "${aws_security_group.default.id}"
  nat_security_group_id = "${aws_security_group.nat.id}"
  region = "${var.region}"
  global_tag_key = "Version"
  global_tag_value = "${var.global_tag_value}"
  resource_postfix = "${var.resource_postfix}"
  resource_prefix = "${var.resource_prefix}"
  default_instance_profile = "${var.resource_prefix}${var.default_instance_profile}"
  resource_instance_profile = "${var.resource_prefix}${var.resource_instance_profile}"
  availability_zone_letter = "${var.az_letter}"

  public_subnet_cidr = "${var.public_subnet_cidr}"
  private_subnet_cidr = "${var.private_subnet_cidr}"

  peering_vpc_owner = "${var.peering_vpc_owner}"
  monitoring_vpc_id = "${var.monitoring_vpc_id}"
  monitoring_vpc_cidr = "${var.monitoring_vpc_cidr}"
  monitoring_vpc_peering_id = "${aws_vpc_peering_connection.monitoring.id}"
  awx_vpc_id = "${var.awx_vpc_id}"
  awx_vpc_cidr = "${var.awx_vpc_cidr}"
  awx_vpc_peering_id = "${aws_vpc_peering_connection.awx.id}"
  awx_security_group_id = "${var.awx_security_group_id}"

  cloud_config_user_data = "${data.template_file.cloud_config.rendered}"
}
