---
# - name: Install OpenJDK
#   yum: name=java-1.7.0-openjdk-headless state=present
#   tags:
#     - kafka
#
# - name: setup group
#   group: name={{kafka_user_group}} system=yes
#   tags:
#     - kafka
#
# - name: Setup user
#   user: name={{kafka_user}} system=yes group={{kafka_user_group}}
#   tags:
#     - kafka
#
# - name: add confluent public key
#   rpm_key: key=https://packages.confluent.io/rpm/5.0/archive.key state=present
#   tags:
#     - kafka
#
# - name: add confluent repository
#   copy: src=confluent-5.0.repo dest=/etc/yum.repos.d/confluent.repo
#   tags:
#     - kafka
#
# - command: yum -y clean all
#   args:
#     warn: no
#
# - name: Install confluent kafka 5.0
#   yum:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - confluent-cli
#     - confluent-kafka-2.11
#     - confluent-support-metrics
#   tags:
#     - kafka
#
# - name: create systemd config
#   template: dest={{kafka_systemd_service}} owner=root group=root mode=644 src=kafka.service.j2
#   register: kafka
#   tags:
#     - kafka
# - command: systemctl daemon-reload
#   when: kafka.changed
#   notify:
#     - restart kafka
#   tags:
#     - kafka
#
# - name: Create log_dir
#   file: path={{kafka_log_dir}} state=directory owner={{kafka_user}} group={{kafka_user_group}} mode=755
#   tags:
#     - kafka
#     - config
#
# # Setup log4j.properties
# - name: create log4j.properties
#   template: dest="{{kafka_conf_dir}}/log4j.properties" owner={{kafka_user}} group={{kafka_user_group}} mode=644 src=log4j.properties.j2
#   notify:
#     - restart kafka
#   tags:
#     - kafka
#     - config
#
# # Setup server.properties
# - name: create server.properties
#   template: dest="{{kafka_conf_dir}}/server.properties" owner={{kafka_user}} group={{kafka_user_group}} mode=640 src=server.properties.j2
#   notify:
#     - restart kafka
#   tags:
#     - kafka
#     - config
#
# - meta: flush_handlers
#   tags:
#   - kafka
#
# - name: Enable kafka
#   service: name=kafka state=started enabled=yes
#   tags:
#     - kafka
#
# - name: wait for kafka port
#   wait_for: host={{kafka_listen_address| default('localhost')}} port={{kafka_port}} state=started timeout={{ kafka_wait_for_period }}
#   when: verify
#   tags:
#     - kafka
#
# - name: test kafka topics command
#   shell: kafka-topics --zookeeper {{zookeeper_hosts}} --list
#   retries: 12
#   delay: 10
#   changed_when: False
#   tags:
#     - kafka
#
# - name: check consul directory
#   file: path=/etc/consul state=directory mode=0777
#   tags:
#     - kafka

- name: generate kafka consul service
  become: yes
  template:
    src: kafka-consul.j2
    dest: "/etc/consul/kafka.json"
  notify:
    - restart consul
  tags:
    - kafka
    - consul
