---
- name: "stop pgbouncer"
  service: name=pgbouncer state=stopped enabled=no
  ignore_errors: yes

- name: "remove pgbouncer"
  yum: pkg=pgbouncer state=removed
  ignore_errors: yes

- name: "remove pgbouncer consul"
  file: path=/etc/consul/pgbouncer-service.json state=absent
  notify:
    - reload consul
  ignore_errors: yes
