---
- hosts: tag_Service_resource
  become: yes
  vars:
    kafka_hosts: "kafka.service.consul:9092"
    kafka_topic: "production.docker.logs"
    schema_registry_url: "http://{{ec2_private_ip_address}}:8081"
  roles:
    - logspout_kafka

- hosts: tag_Service_controller:tag_Service_edge
  become: yes
  vars:
    kafka_hosts: "kafka.service.consul:9092"
    kafka_topic: "production.docker.logs"
    schema_registry_url: "http://agent.mesos.service.consul:8081"
  roles:
    - logspout_kafka
