---
- hosts: tag_Service_resource
  roles:
    - marathon_deploy
  vars:
    marathon_apps:
      - app:
          id: "/metrics/influxdb"
          instances: 1
          cpus: 1
          mem: 6144
          container:
            type: "DOCKER"
            docker:
              image: "influxdb:1.5"
              network: "HOST"
              parameters:
                - {key: 'volume-driver', value: 'rexray'}
                - {key: 'volume', value: 'metrics-influxdb:/var/lib/influxdb'}
          ports: [4242]
          requirePorts: true
          env:
            INFLUXDB_ADMIN_ENABLED: "true"
            INFLUXDB_OPENTSDB_0_ENABLED: "true"
            INFLUXDB_OPENTSDB_DATABASE: "metrics"
          labels:
            MARATHON_SINGLE_INSTANCE_APP: "true"
            overrideTaskName: "influxdb"
          upgradeStrategy:
            minimumHealthCapacity: 0
            maximumOverCapacity: 0
          healthChecks:
            - protocol: "MESOS_HTTP"
              gracePeriodSeconds: 60
              intervalSeconds: 5
              port: 8086
              path: "/ping"
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - app:
          id: "/metrics/grafana"
          instances: 1
          cpus: 1
          mem: 2048
          container:
            type: "DOCKER"
            docker:
              image: "grafana/grafana:6.1.3"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 3000, hostPort: 0, protocol: 'tcp'}
              parameters:
                - {key: 'volume-driver', value: 'rexray'}
                - {key: 'volume', value: 'metrics-grafana:/var/lib/grafana'}
          env:
            GF_SERVER_ROOT_URL: "https://grafana.upgrade.tmagentsystem.com"
          labels:
            MARATHON_SINGLE_INSTANCE_APP: "true"
            overrideTaskName: "grafana"
            tags: "external,http"
          upgradeStrategy:
            minimumHealthCapacity: 0
            maximumOverCapacity: 0
          healthChecks:
            - protocol: "MESOS_HTTP"
              gracePeriodSeconds: 60
              intervalSeconds: 5
              portIndex: 0
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - app:
          id: "/metrics/lenses"
          instances: 1
          cpus: 2
          mem: 6144
          container:
            type: DOCKER
            docker:
              image: lensesio/lenses:4.1.1
              network: BRIDGE
              portMappings:
              - containerPort: 9991
                hostPort: 9991
                protocol: tcp
              parameters:
              - key: volume-driver
                value: rexray
              - key: volume
                value: metrics-lenses-storage:/data/storage
          env:
            LENSES_PORT: '9991'
            DEBUG_SCRIPT: 'true'
            LENSES_KAFKA_BROKERS: PLAINTEXT://devcluster-kafka-0.node.dc1.consul:9092
            LENSES_KAFKA_METRICS: '{type:"JMX", default.port: 7999}'
            LENSES_ZOOKEEPER_HOSTS: '[{url:"devcluster-controller-0.node.dc1.consul:2181"}]'
            LENSES_SCHEMA_REGISTRY_URLS: '[{url:"http://kafka-schema.service.consul:8081"}]'
            LENSES_KAFKA_CONNECT_CLUSTERS: '[{name:"jangl",urls:[{url:"http://devcluster-kafka-connect-0.node.dc1.consul:8083",metrics:{type: "JMX", url: "devcluster-kafka-connect-0.node.dc1.consul:7999"}}],statuses:"__connect-status",configs:"__connect-config",offsets:"__connect-offsets"}]'
            LENSES_SCHEMA_REGISTRY_TOPICS: _kafka_schemas
            LENSES_SQL_EXECUTION_MODE: CONNECT
            LENSES_SQL_STATE_DIR: /var/run/lenses-sql-kstream-state
            LENSES_SECURITY_USER: admin
            LENSES_SECURITY_PASSWORD: sha256:8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            LICENSE: '{"source":"Lenses.io Ltd","clientId":"3ca02ea8-7009-41c7-88d3-0f1a87ac4b8e","details":"Lenses","key":"eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0.SajxdjXneFXQVndFyoS05SiasWzvH_qEuUTegLd4HERHNze6lRTLcw.A8BMND8H1BxcWzY5kCEInA.C-mfI-yEHrpZ1u38XKY8TXe2m-22vy7rrihwwVU_rd1Ml6WOt5y44PbZeSEqUqCA4GxnuSSxZyhBqw-5urePZIL7HG6KiG_xToh62nQQX4n4WeHYf7dGJh9k16IohKCz3LGj3YfJUdih07BKNdbHstdnNsxyDx8rb3xtrLVx24l1VIg-iUsNomXFJ5MHw9oGhGvWaAPl87moh-T-8kuqrfESX_TWDTLGWTjA9M7cyY1n3da_05oQYL_bXk2SQBCCzhAJiBeWDbxgirSXd-sAyG83wLDO0tR5J-sJ9CCAPa05EWXJxuAGEQB7Bq6zVZB4dA1W259Y3I7KvE0m_vAIG_CD3YkHlvnFsYrkQ0kKFxf79lRozXCvnk5aJfrBTDZq8ufy2Hml26Xfbu_PpA88b6KiB18vdp1tQoX9M5uOqtWsQCVNWGNteanZfeoEYN6QtqVPWT6YVkMBa-hrp3wc7y57rSnO6qJHWtKkQgyyHgGBTzGE-d-qf71K4KwYjfxYDgS2uoB-P0r2JAw9NQHYjlaVEX-i-DgcqpVOT8jXX87oX0EpUyZy7E5MbTAaRnkn_hOP2-VaR04UUVIoGsEqXAa54Dku4yf25Sh85qvzi5tw7YAiIJqbAOCu-ySHAajnrMjKn5Zpkk9GqtJAgR53q4uzVtMuJtBJlZhkXsikrSvjrl5gOuq9xgPH-f6NHutcd9TYRIqjLNCeMic8D5HJbdBDilapSe-zjgq2S73spXzTeULBzlQLzlyNvbSnRD4mMfPJ104dqv6plUmPwF7IiGFoICUsw-TQtLatBtU3sgmrJx4fCAbToBk-HTRhdC9IeqZ5PI3Oty-LIsfQ2RTtYgc7TJMrG_ecgOUugyqA4fGOJOR1r20tDXqs0jvgo0cj7xBs7GB-HhaByNCQNIR9JUSCsCaw9UnLkpqWhEesBzRx4x_yMey8Bin18Xa8TpVuzXxHcZHDI62ePNcpn9DSDjbV4TpvzrDGJu5JOAW8vTps0yu8Zw944wU24uoaRuygau8Gi2BWSDKyXAHq3nC4uRMmo7XcTbYldZHRxpug4e8sH3El9eeSCXF65DH4ynqRzc694_PHn7xsjG88FrY12rOpv3JPwp1yIWDVXHWFkunHnfiaMYcV3_7_kGn2Ru-rtR6-60_yOaAgMNW-ydpVOAC2vl5AGQya4Rr0DklUIV-cJn3_W-_xp7aS7K4kvtaJBK6BGW2IUm9xToAw9YrUNKVZEZxuuv32wKzhQUfRLebPNmGZdz0CHuFSPntb1udwaPvMlnf706AAUwe37yW02iIzIBgPajMzqgv-nD29BsKdyZxR3_zIZyYa9ghUaToa.dnM0j1SwHEQjfGEac0CgWA"}'
          labels:
            MARATHON_SINGLE_INSTANCE_APP: 'true'
            overrideTaskName: lenses
            tags: backend,http
          healthChecks:
          - protocol: HTTP
            gracePeriodSeconds: 300
            intervalSeconds: 15
            portIndex: 0
            path: "/"
            timeoutSeconds: 5
            maxConsecutiveFailures: 3
          upgradeStrategy:
            minimumHealthCapacity: 0
            maximumOverCapacity: 0
