- name: Stop kafka
  service: name=kafka state=stopped enabled=no

- name: Removing Kafka package
  yum: name=confluent-kafka-2.11 state=absent

- name: Removing Confluent platform
  yum: name=confluent-platform-2.11 state=absent

- name: Removing Confluent repo
  file: path=/etc/yum.repos.d/confluent.repo state=absent
