---

- name: stop marathon
  service: name=marathon state=stopped
- name: rm marathon files
  file: path="{{ item }}" state=absent
  loop:
    - /etc/default/marathon
    - /etc/systemd/system/marathon.service
    - /usr/share/marathon
    - /usr/lib/systemd/system/marathon.service
    - /usr/lib/systemd/system/marathon.service.d
- name: uninstall marathon
  yum: name=marathon state=absent
