---
- hosts: tag_Service_kafka
  become: yes
  tasks:
    - name: "stop kafka"
      service: name=kafka state=stopped
      ignore_errors: yes

    - name: "stop consul"
      service: name="{{item}}" state=stopped enabled=no
      ignore_errors: yes
      with_items:
        - consul
        - socat-consul
        - nginx-consul

    - name: "remove consul"
      yum: pkg="{{item}}" state=removed
      ignore_errors: yes
      with_items:
        - consul
        - consul-ui

    - name: "remove consul conf"
      file: path=/etc/consul state=absent
      ignore_errors: yes
