---

- hosts: tag_Service_controller
  become: yes
  vars:
    consul_is_server: true
#  serial: 1
  roles:
    - consul_remove
    - consul
    - docker
    - marathon
    - zookeeper

- hosts: tag_Service_resource
  become: yes
  roles:
    - consul_remove
    - consul
    - docker
    - pgbouncer

- hosts: tag_Service_edge:tag_Service_vpn
  become: yes
  # serial: 1
  roles:
    - consul_remove
    - consul
    - docker

- hosts: tag_Service_kafka
  become: yes
  # serial: 1
  roles:
    - consul_remove
    - consul
    - kafka

- hosts: tag_Service_kafka_zk
  become: yes
  vars:
    zookeeper_service_name: "kafka-zk"
    zookeeper_ensemble: "kafka"
    zookeeper_s3_prefix: "kafka"
  roles:
    - consul_remove
    - consul
    - zookeeper

- hosts: tag_Service_resource:tag_Service_edge
  become: yes
  tasks:
    - name: restart nginx-consul
      service: name=nginx-consul enabled=yes state=restarted
  ignore_errors: yes
  tags: ["consul"]
