---
- hosts: tag_Service_resource
  serial: "75%"
  vars:
    mesos_mode: follower
  handlers:
    - include: ../roles/mesos/handlers/main.yml
      become: yes
  tasks:
    - name: set consul maintenance enable
      become: yes
      command: consul maint -enable -reason "{{ lookup('env', 'USER') }} upgrading Mesos"

    - name: stop and disable mesos-slave
      become: yes
      service:
        name: mesos-slave
        state: stopped
        enabled: no

    - name: remove mesos
      become: yes
      yum:
        name: mesos
        state: absent

    - name: remove etc directory
      become: yes
      file:
        dest: "/etc/{{ item }}"
        state: absent
      with_items:
        - mesos-slave

    - include: ../roles/mesos/tasks/main.yml
      become: yes
    - include: ../roles/mesos_slave/tasks/main.yml
      become: yes

    - name: set consul maintenance disable
      become: yes
      command: consul maint -disable

- hosts: tag_Service_controller
  serial: "{{ serial | default(1) }}"
  vars:
    mesos_mode: leader
  handlers:
    - include: ../roles/mesos/handlers/main.yml
      become: yes
  tasks:
    - name: set consul maintenance enable
      become: yes
      command: consul maint -enable -reason "{{ lookup('env', 'USER') }} upgrading Mesos and Marathon"

    - name: stop and disable mesos
      become: yes
      service:
        name: mesos
        state: stopped
        enabled: no

    - name: stop and disable marathon
      become: yes
      service:
        name: marathon
        state: stopped
        enabled: no
        
    # mesos
    - name: remove mesos
      become: yes
      yum:
        name: mesos
        state: absent

    # marathon
    - name: remove marathon
      become: yes
      yum:
        name: mesos
        state: absent

    - name: remove etc directories
      become: yes
      file:
        dest: "/etc/{{ item }}"
        state: absent
      with_items:
        - marathon/conf
        - mesos-master


    - set_fact: mesos_mode=leader

    - include: ../roles/mesos/tasks/main.yml
      become: yes
    - include: ../roles/mesos_master/tasks/main.yml
      become: yes

    - name: set consul maintenance disable
      become: yes
      command: consul maint -disable

#- hosts: tag_Service_resource
#  serial: "{{ serial | default(1) }}"
#  tasks:
#    # collectd gets confused after the mesos upgrade
#    - name: restart collectd
#      become: yes
#      service:
#        name: collectd
#        state: restarted
#        
#- hosts: tag_Service_controller
#  serial: "{{ serial | default(1) }}"
#  tasks:
#    # collectd gets confused after the mesos upgrade
#    - name: restart collectd
#      become: yes
#      service:
#        name: collectd
#        state: restarted        