---
# - hosts: tag_Service_kafka
#   become: yes
#   tasks:
#     # lineinfile replace
#     # ensure that old version stays running
#     # update conf files with new settings, not in effect yet.
#     - lineinfile: dest=/etc/kafka/server.properties state=present regexp='^inter.broker.protocol.version\=' line='inter.broker.protocol.version=1.0.0' create=yes
#     - lineinfile: dest=/etc/kafka/server.properties state=present regexp='^log.message.format.version\=' line='log.message.format.version=1.0.0' create=yes
#   serial: "100%"
#
# - hosts: tag_Service_kafka
#   become: yes
#   roles:
#     # stop service
#     # remove old version
#     - role: kafka_remove
#
#     # install new version
#     # start service
#     - role: kafka
#   serial: 1

- hosts: tag_Service_kafka
  become: yes
  tasks:
    # lineinfile replace
    # update conf to new versions
    - lineinfile: dest=/etc/kafka/server.properties state=present regexp='^inter.broker.protocol.version\=' line='inter.broker.protocol.version=1.0' create=yes
    - lineinfile: dest=/etc/kafka/server.properties state=present regexp='^log.cleaner.enable\=' line='log.cleaner.enable=true' create=yes

  serial: "100%"

- hosts: tag_Service_kafka
  become: yes
  tasks:
    # restart service
    - service: name=kafka state=restarted
  serial: 1

- hosts: tag_Service_kafka
  become: yes
  tasks:
    # lineinfile replace
    # update conf to new versions
    - lineinfile: dest=/etc/kafka/server.properties state=present regexp='^log.message.format.version\=' line='log.message.format.version=1.0' create=yes
  serial: "100%"

- hosts: tag_Service_kafka
  become: yes
  tasks:
    # restart service
    - service: name=kafka state=restarted
  serial: 1
