---
- name: create nginx configuration directories
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /etc/nginx
    - /etc/nginx/templates
  tags:
    - nginx

- name: add luameter
  become: yes
  unarchive:
    src: luameter.tgz
    dest: /etc/nginx/
    owner: root
    group: root
  tags:
    - nginx

- include: sysctl.yml
  tags:
    - nginx
    - sysctl

- name: copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx-consul
  tags:
    - nginx

- name: "create htpasswd"
  file:
    state: touch
    dest: "/etc/nginx/.htpasswd"
    owner: "root"
    group: "root"
    mode: 0644
  tags:
    - nginx

- name: deploy nginx service
  become: yes
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
  with_items:
   - src: nginx-consul.service.j2
     dest: /usr/lib/systemd/system/nginx-consul.service
   - src: nginx-consul.env.j2
     dest: /etc/default/nginx-consul.env
  notify:
    - reload systemd
    - restart nginx-consul
  tags:
    - nginx

- name: enable nginx-consul
  become: yes
  service:
    name: nginx-consul
    enabled: yes
    state: started
  tags:
    - nginx
