---

- name: check consul directory
  file: path=/etc/consul state=directory mode=0777
  tags:
    - consul
    - kafka_connect

- name: generate kafka connect consul services
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: kafka-connect-consul.json.j2
      dest: /etc/consul/kafka-connect-consul.json
  notify:
    - reload consul
  tags:
    - consul
    - kafka_connect


- name: kafka-connect docker container
  docker_container:
    name: kafka-connect
    image: "{{ kafka_connect_image }}:{{ kafka_connect_version }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "8083:8083"
    env:
      CONNECT_REST_ADVERTISED_HOST_NAME: "{{ ec2_tag_Name }}.node.dc1.consul"
      CONNECT_BOOTSTRAP_SERVERS: "{{ kafka_broker_endpoint }}"
      CONNECT_CONFIG_STORAGE_TOPIC: "__connect-config"
      CONNECT_GROUP_ID: "compose-connect-group"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "{{ schema_registry_endpoint }}"
      CONNECT_OFFSET_STORAGE_TOPIC: "__connect-offsets"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
      CONNECT_STATUS_STORAGE_TOPIC: "__connect-status"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "{{ schema_registry_endpoint }}"
      KAFKA_HEAP_OPTS: "-Xms{{ jvm_starting_heap_size }} -Xmx{{ jvm_maximum_heap_size }} -XX:MetaspaceSize={{ jvm_heap_metaspace_size }} -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
      KAFKA_JMX_PORT: "7999"
  tags:
    - kafka_connect

- wait_for: port=8083 timeout=60 host={{ ansible_default_ipv4.address }}
  tags:
    - kafka_connect
    - test

- name: checking kafka connect status
  uri:
    url: http://{{ ansible_default_ipv4.address }}:8083/connectors
  tags:
    - kafka_connect
    - test

- meta: flush_handlers
