---
- hosts: tag_Service_resource
  roles:
    - marathon_deploy
  vars:
    marathon_apps:
      - app:
          id: "/redis/shared-cache"
          instances: 1
          cpus: 0.5
          mem: 1024
          container:
            type: "DOCKER"
            docker:
              image: "redis:4"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 6379, hostPort: 6379, protocol: 'tcp'}
          healthChecks:
            - protocol: "TCP"
              gracePeriodSeconds: 10
              intervalSeconds: 5
              portIndex: 0
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - app:
          id: "/redis/persist-cache"
          instances: 1
          cpus: 0.5
          mem: 1024
          container:
            type: "DOCKER"
            docker:
              image: "redis:5"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 6379, hostPort: 6378, protocol: 'tcp'}
              parameters:
                - {key: 'volume-driver', value: 'rexray'}
                - {key: 'volume', value: 'persist-cache-redis:/data'}
          labels:
            MARATHON_SINGLE_INSTANCE_APP: "true"
          upgradeStrategy:
            minimumHealthCapacity: 0
            maximumOverCapacity: 0
          healthChecks:
            - protocol: "TCP"
              gracePeriodSeconds: 10
              intervalSeconds: 5
              portIndex: 0
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - app:
          id: "/redis/caps"
          instances: 1
          cpus: 0.5
          mem: 1024
          container:
            type: "DOCKER"
            docker:
              image: "redis:4"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 6379, hostPort: 6377, protocol: 'tcp'}
              parameters:
                - {key: 'volume-driver', value: 'rexray'}
                - {key: 'volume', value: 'caps-redis:/data'}
          labels:
            MARATHON_SINGLE_INSTANCE_APP: "true"
          upgradeStrategy:
            minimumHealthCapacity: 0
            maximumOverCapacity: 0
          healthChecks:
            - protocol: "TCP"
              gracePeriodSeconds: 10
              intervalSeconds: 5
              portIndex: 0
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - app:
          id: "/redis/pingpost"
          instances: 1
          cpus: 0.5
          mem: 1024
          container:
            type: "DOCKER"
            docker:
              image: "redis:4"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 6379, hostPort: 6376, protocol: 'tcp'}
              parameters:
                - {key: 'volume-driver', value: 'rexray'}
                - {key: 'volume', value: 'pingpost-redis:/data'}
          labels:
            MARATHON_SINGLE_INSTANCE_APP: "true"
          upgradeStrategy:
            minimumHealthCapacity: 0
            maximumOverCapacity: 0
          healthChecks:
            - protocol: "TCP"
              gracePeriodSeconds: 10
              intervalSeconds: 5
              portIndex: 0
              timeoutSeconds: 5
              maxConsecutiveFailures: 3
