---
- name: Installing requirements
  become: yes
  run_once: true
  pip: name=marathon version=0.11.0 state=present
  tags: ["marathon"]

- name: Running migration commands
  become: yes
  run_once: true
  docker_container:
    name: "migrate-command"
    image: "{{ item.image }}"
    command: "{{ item.command }}"
    env: "{{ item.env | default({}) | combine({'HOST': ec2_private_ip_address}) }}"
    state: started
    detach: False
    cleanup: True
  register: migrate_command
  loop: "{{ migrate_commands | default([]) | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.name }}"
  tags: ["migrate"]

- name: 'Migration results'
  debug: msg="{{ item.ansible_facts.docker_container.Output }}"
  run_once: true
  loop: "{{ migrate_command.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  tags: ["migrate"]

- name: Launch marathon apps
  run_once: true
  marathon:
    uri: "{{ marathon_uri }}"
    app: "{{ item.app | combine(deploy.get(item.get('name'), {}), recursive=True) | to_json }}"
    state: updated
  loop: "{{ marathon_apps | default([]) | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.name | default(item.app) }}"
  tags: ["marathon"]
