---

- name: sysctl net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "4096 87380 16777216"
    state: present

- name: sysctl net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 65536 16777216"
    state: present

- name: sysctl net.core.rmem_max
  sysctl:
    name: net.core.rmem_max
    value: "67108864"
    state: present

- name: sysctl net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: "67108864"
    state: present

- name: sysctl net.core.netdev_max_backlog
  sysctl:
    name: net.core.netdev_max_backlog
    value: "30000"
    state: present

- name: sysctl net.core.somaxconn
  sysctl:
    name: net.core.somaxconn
    value: "2048"
    state: present

- name: sysctl net.ipv4.tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: "450000"
    state: present

- name: sysctl net.ipv4.tcp_timestamps
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: "0"
    state: present

- name: sysctl net.ipv4.tcp_sack
  sysctl:
    name: net.ipv4.tcp_sack
    value: "1"
    state: present

- name: sysctl net.ipv4.tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: "15"
    state: present

- name: sysctl net.ipv4.tcp_keepalive_time
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: "60"
    state: present

- name: sysctl net.ipv4.tcp_keepalive_intvl
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: "10"
    state: present

- name: sysctl net.ipv4.tcp_keepalive_probes
  sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: "3"
    state: present

- name: sysctl net.ipv4.tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: "1"
    state: present
