- name: enable yum repos
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - ciscocloud-rpm.repo
  tags:
    - bootstrap

- name: enable templated yum repos
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - asteris-mantl-rpm.repo
  tags:
    - bootstrap
