---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: reload consul
  become: yes
  command: /usr/local/bin/consul reload
  notify:
    - wait for consul to listen

- name: restart consul
  become: yes
  command: systemctl restart consul
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  command: /usr/local/bin/consul-wait-for-leader.sh

- name: reload consul-template
  become: yes
  command: systemctl reload consul-template

- name: reload nginx
  become: yes
  command: systemctl reload nginx-consul
