---
consul_version: '1.8.0'
consul_package_name: "consul_1.8.0_linux_amd64.zip"
consul_package_checksum: "98df3e0a8ede84794fa4d20b1b6b5d52ad3b983dec916c4d612cecba7c48a421"
consul_package_repository: https://releases.hashicorp.com/consul
consul_package_url: "{{ consul_package_repository }}/{{ consul_version }}/{{ consul_package_name }}"

consul_dns_domain: consul
consul_group: 'consul'
consul_user: 'consul'
consul_install_path: '/usr/local/bin'
consul_data_path: '/var/lib/consul'
consul_config_path: '/etc/consul'

consul_servers_group: tag_Service_controller
consul_is_server: "{{ consul_servers_group in group_names }}"

consul_conf_datacenter: 'dc1'
consul_conf_bootstrap: false
consul_conf_bootstrap_expect: "{{ groups[consul_servers_group] | length }}"
consul_conf_advertise_addr: "{{ ansible_default_ipv4.address }}"
consul_conf_bind_addr: 0.0.0.0
consul_conf_client_addr: 0.0.0.0
consul_conf_addresses_dns: 0.0.0.0
consul_conf_addresses_http: 0.0.0.0
consul_conf_data_dir: "{{ consul_data_path }}"
consul_conf_log_level: 'info'
# consul_conf_log_level: 'err'
consul_conf_node_name: "{{ ec2_tag_Name }}"
consul_conf_leave_on_terminate: true
consul_conf_retry_join:
  - "provider=aws tag_key=Service tag_value=controller"
consul_conf_retry_interval: 30s
consul_conf_enable_script_checks: true
consul_conf_disable_update_check: true

consul_conf_node_ttl: 5s
consul_conf_service_ttl: 5s
