---
- hosts: tag_Service_resource
  roles:
    - marathon_deploy
  vars:
    jangl_billing_docker_image: "docker.jangl.com/jangl-billing:{{ jangl_billing_version | default('latest') }}"
    jangl_merchant_docker_image: "docker.jangl.com/jangl-merchant:{{ jangl_merchant_version | default('latest') }}"
    jangl_platform_fees_docker_image: "docker.jangl.com/jangl-platform-fees:{{ jangl_platform_fees_version | default('latest') }}"

    marathon_apps:
      - name: jangl_billing
        app: &marathon-app
          id: billing/jangl-billing
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_billing_docker_image }}"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 9000, hostPort: 0, protocol: 'tcp'}
          env: "{{ deploy.jangl_billing.env }}"
          instances: 1
          cpus: 0.5
          mem: 1024
          labels:
            tags: "backend,uwsgi"
            overrideTaskName: "billing"
          fetch:
            - uri: "file:///etc/docker.tar.gz"
          healthChecks:
            - protocol: "COMMAND"
              command: "uwsgi --ping $HOST:$PORT0"
              gracePeriodSeconds: 10
              intervalSeconds: 15
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - name: jangl_billing_balance_worker
        app:
          << : *marathon-app
          id: billing/balance-worker
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_billing_docker_image }}"
          env: "{{ deploy.jangl_billing.env }}"
          cmd: "./manage.py workers update_account_balance"
          cpus: 0.3
          labels: {}
          healthChecks: []

      - name: jangl_billing_transaction_worker
        app:
          << : *marathon-app
          id: billing/transaction-worker
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_billing_docker_image }}"
          env: "{{ deploy.jangl_billing.env }}"
          cmd: "./manage.py workers create_account_transactions"
          cpus: 0.3
          labels: {}
          healthChecks: []

      - name: jangl_merchant
        app:
          << : *marathon-app
          id: billing/jangl-merchant
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_merchant_docker_image }}"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 9000, hostPort: 0, protocol: 'tcp'}
          env: "{{ deploy.jangl_merchant.env }}"
          labels:
            tags: "backend,uwsgi"
            overrideTaskName: "merchant"

      - name: jangl_platform_fees
        app:
          << : *marathon-app
          id: billing/platform-fees
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_platform_fees_docker_image }}"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 9000, hostPort: 0, protocol: 'tcp'}
          env: "{{ deploy.jangl_platform_fees.env }}"
          labels:
            tags: "backend,uwsgi"
            overrideTaskName: "platform-fees"

      - name: jangl_platform_fees_workers
        app:
          << : *marathon-app
          id: billing/platform-fees-workers
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_platform_fees_docker_image }}"
          env: "{{ deploy.jangl_platform_fees.env }}"
          cmd: "./manage.py workers"
          cpus: 0.3
          labels: {}
          healthChecks: []

    migrate_commands:
      - name: Migrate Billing DB
        image: "{{ jangl_billing_docker_image }}"
        command: "./manage.py migrate --database=default"
        env: "{{ deploy.jangl_billing.env }}"

      - name: Migrate Platform Fees DB
        image: "{{ jangl_platform_fees_docker_image }}"
        command: "./manage.py migrate --database=default"
        env: "{{ deploy.jangl_platform_fees.env }}"
