---
- hosts: tag_Service_resource
  roles:
    - marathon_deploy
    - chronos_deploy
  vars:
    jangl_webleads_docker_image: "docker.jangl.com/jangl-webleads:{{ jangl_webleads_version | default('latest') }}"
    jangl_webleads_api_docker_image: "docker.jangl.com/jangl-webleads-api:{{ jangl_webleads_api_version | default('latest') }}"

    marathon_apps:
      - name: jangl_webleads
        app: &marathon-app
          id: webleads/jangl-webleads
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_webleads_docker_image }}"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 9000, hostPort: 0, protocol: 'tcp'}
          env: "{{ deploy.jangl_webleads.env }}"
          instances: 1
          cpus: 0.3
          mem: 1024
          labels:
            tags: "backend,uwsgi"
            overrideTaskName: "webleads"
          fetch:
            - uri: "file:///etc/docker.tar.gz"
          healthChecks:
            - protocol: "COMMAND"
              command: "uwsgi --ping $HOST:$PORT0"
              gracePeriodSeconds: 10
              intervalSeconds: 15
              timeoutSeconds: 5
              maxConsecutiveFailures: 3

      - name: jangl_webleads_workers
        app:
          << : *marathon-app
          id: webleads/pingpost-worker
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_webleads_docker_image }}"
          args: ["./manage.py", "run_ping_post_pricing"]
          labels: {}
          healthChecks: []

      - name: jangl_webleads_export
        app:
          << : *marathon-app
          id: webleads/export-worker
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_webleads_docker_image }}"
          args: ["./manage.py", "workers", "export_leads"]
          labels: {}
          healthChecks: []

      - name: jangl_webleads_returns
        app:
          << : *marathon-app
          id: webleads/returns-worker
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_webleads_docker_image }}"
          args: ["./manage.py", "workers", "dispute_lead"]
          labels: {}
          healthChecks: []

      - name: jangl_webleads_api
        app:
          << : *marathon-app
          id: webleads/webleads-api
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_webleads_api_docker_image }}"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 9000, hostPort: 0, protocol: 'tcp'}
          env: "{{ deploy.jangl_webleads_api.env }}"
          labels:
            tags: "external,uwsgi,cors"
            overrideTaskName: "api"

      - name: jangl_webleads_test_api
        app:
          << : *marathon-app
          id: webleads/webleads-test-api
          container:
            type: "DOCKER"
            docker:
              image: "{{ jangl_webleads_api_docker_image }}"
              network: "BRIDGE"
              portMappings:
                - {containerPort: 9000, hostPort: 0, protocol: 'tcp'}
          env: "{{ deploy.jangl_webleads_api.env | combine({'TEST_API': 'True'}) }}"
          labels:
            tags: "external,uwsgi,cors"
            overrideTaskName: "test-api"

    migrate_commands:
      - name: Migrate Webleads DB
        image: "{{ jangl_webleads_docker_image }}"
        command: "sh -c './manage.py migrate --database=default && ./manage.py migrate'"
        env: "{{ deploy.jangl_webleads.env }}"

    chronos_jobs:
      - name: jangl-webleads-sell_captured_leads
        command: "./manage.py sell_captured_leads"
        docker_image: "{{ jangl_webleads_docker_image }}"
        env: "{{ deploy.jangl_webleads.env | chronos_env }}"
        start_time: "2020-01-01T00:00:00Z"
        run_interval: PT2M
        shell: true
        cpus: 0.5
        disk: 256
        mem: 1024
        epsilon: PT1M
