---

- name: check consul directory
  file: path=/etc/consul state=directory mode=0777
  tags:
    - consul

- name: generate kafka connect consul services
  become: yes
  template:
    src: kafka-connect-consul.json.j2
    dest: /etc/consul/kafka-connect-consul.json
  notify:
    - reload consul
  tags:
    - consul
