---

- name: Prepare lenses SQL connect
  file: path="{{lenses_sql_connect_path}}" state=directory

- name: Download lenses SQL connect
  become: yes
  unarchive:
    src: "{{lenses_sql_connect_url}}"
    dest: "{{lenses_sql_connect_path}}"
    remote_src: yes
    extra_opts:
    - "--wildcards"
    - "*/connector/*"
    - "--strip-components=2"

- name: configure lvm for lenses
  become: yes
  template:
    src: lenses-volume.conf.j2
    dest: /etc/mantl/filesystems.d/20-lenses-volume.conf
    mode: 0644
  notify:
    - reload lvm config
  when: uses_lvm

- meta: flush_handlers

- name: Create lenses SQL state directory
  become: yes
  file: path="{{lenses_sql_state_path}}" state=directory owner=cp-kafka-connect group=confluent
