---
- name: Set marathon config
  template: src=marathon.j2 dest=/etc/default/marathon
  notify: Restart marathon

- name: write marathon service file
  become: yes
  template:
    src: marathon.service.j2
    dest: /etc/systemd/system/marathon.service
    mode: 0600
  notify:
    - Restart marathon

- name: Create /usr/lib/systemd/system/marathon.service.d directory
  file: path=/usr/lib/systemd/system/marathon.service.d state=directory owner=root group=root mode=0755

- name: Systemd environment variables
  template: src=marathon_environment.j2 dest=/usr/lib/systemd/system/marathon.service.d/marathon-environment.conf
  notify:
    - Reload daemon
    - Restart marathon

- name: create marathon directory
  become: yes
  file:
    dest: /etc/marathon
    state: directory
    mode: 0755

- name: create marathon store directory
  become: yes
  file:
    dest: /etc/marathon/store
    state: directory
    mode: 0600

- name: create marathon apps directory
  become: yes
  file:
    dest: /etc/marathon/apps
    state: directory
    mode: 0600
