---
- name: set timezone to etc/utc
  become: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes
  tags:
    - bootstrap

- name: preserve hostname
  become: yes
  copy:
    src: 02_hostname.cfg
    dest: /etc/cloud/cloud.cfg.d/02_hostname.cfg
    owner: root
    group: root
    mode: 0644
  tags:
    - bootstrap

- name: set persistent hostname
  become: yes
  copy:
    dest: /etc/hostname
    content: "{{ ec2_tag_Name }}{% if use_host_domain %}.{{ host_domain }}{% endif %}"
    force: yes
    owner: root
    group: root
    mode: 0644
  tags:
    - bootstrap

- name: set current hostname
  become: yes
  shell: "hostname {{ ec2_tag_Name }}{% if use_host_domain %}.{{ host_domain }}{% endif %}"
  tags:
    - bootstrap

- name: enable EPEL repo
  become: yes
  yum:
    name: epel-release
    state: latest
  tags:
    - bootstrap

- name: enable powertools
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - yum update cache
  tags:
    - bootstrap

- meta: flush_handlers

- name: install system utilities
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - chrony
    - curl
    - httpd-tools
    - java-1.8.0-openjdk
    - jq
    - nc
    - openssh
    - policycoreutils-python3
    - python2
    - python2-pip
    - python3
    - python3-pip
    - python3-libselinux
    - system-storage-manager
    - unzip
  tags:
    - bootstrap

- name: Install bundled binaries
  copy:
    src: "{{item}}"
    dest: "/usr/bin/{{item}}"
    owner: root
    group: root
    mode: 0755
  loop:
    - consul-cli
    - smlr
    - zookeepercli

- name: update setuptools and pip
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - setuptools
  tags:
    - bootstrap

- name: enable chronyd
  become: yes
  service:
    name: chronyd
    enabled: yes
    state: started
  tags:
    - bootstrap

- name: make logrotate daily
  replace:
    dest: /etc/logrotate.conf
    regexp: '^weekly'
    replace: 'daily'
  tags:
    - bootstrap
    - logrotate

- name: make logrotate only 1 day
  replace:
    dest: /etc/logrotate.conf
    regexp: '^#?rotate.+'
    replace: 'rotate 1'
  tags:
    - bootstrap
    - logrotate

- name: make logrotate compressed
  replace:
    dest: /etc/logrotate.conf
    regexp: '^#?compress'
    replace: 'compress'
  tags:
    - bootstrap
    - logrotate

- name: disable requiretty in sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ^.+requiretty$
    line: "# Defaults	requiretty"
  tags:
    - bootstrap

- name: configure selinux
  become: yes
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  tags:
    - bootstrap

- include: ssh.yml
# - include: journald.yml
- include: sysctl.yml
  tags: ["sysctl"]
# - include: fail2ban.yml
- include: nvme.yml
  tags: ["nvme"]
