---
- hosts: tag_Service_controller
  become: yes
  gather_facts: yes
  vars:
    consul_is_server: true
    mesos_install_mode: "master"
  roles:
    - consul
    - dnsmasq
    - docker
    - zookeeper
    - mesos
    - marathon
    - chronos
