---
- hosts: tag_Service_kafka_zk
  become: yes
  vars:
    zookeeper_server_group: "tag_Service_kafka_zk"
    zookeeper_service_name: "kafka-zk"
  roles:
    - consul
    - dnsmasq
    - confluent.common
    - confluent.zookeeper
