---
- hosts: tag_Service_vpn
  become: yes
  tasks:
    - name: zabbix-proxy
      docker_container:
        name: zabbix-proxy
        state: started
        restart_policy: always
        image: zabbix/zabbix-proxy-sqlite3:alpine-4.0.3
        ports:
          - "10051:10051"
        env:
          ZBX_HOSTNAME: "{{ ec2_tag_Name }}"
          ZBX_SERVER_HOST:  "monitor.jangl.com"
          # update frequently so  autodiscovered hosts are pushed down before
          # zabbix starts complaining they can't be reached.
          # and active jobs get pushed out in a more timely manner.
          ZBX_CONFIGFREQUENCY: "30"
      tags: ["zabbix"]

- hosts: tag_Service_vpn:tag_Service_controller:tag_Service_edge:tag_Service_resource
  become: yes
  tasks:
    - name: zabbix-agent
      docker_container:
        name: zabbix-agent
        state: started
        restart_policy: always
        image: zabbix/zabbix-agent:alpine-4.0.3
        privileged: yes
        network_mode: host
        pid_mode: host
        env:
          ZBX_HOSTNAME: "{{ ec2_tag_Name }}"
          ## should point to the zabbix-proxy, which is the vpn server in our setup.
          ZBX_SERVER_HOST:  "vpn.service.consul"
      tags: ["zabbix"]
