---
mesos_install_mode: "slave" # {master|slave|master-slave}
mesos_version: 1.7.3
mesosphere_yum_repo: "https://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-2.noarch.rpm"

mesos_rpm_url: "https://files.jan.gl/repos/RPMS/el8/mesos-1.7.3-0.1.20201127085232.el8.x86_64.rpm"
# conf file settings
mesos_cluster_name: "jangl"
mesos_ip: "{{ ansible_default_ipv4.address }}"
mesos_hostname: "{{ ansible_default_ipv4.address }}"
mesos_master_port: "5050"
mesos_slave_port: "5051"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 16384"
mesos_work_dir: "/var/lib/mesos"

mesos_leaders_group: tag_Service_controller
mesos_quorum: "{{ groups[mesos_leaders_group]|count // 2 + 1 }}"

zookeeper_dns: "zookeeper.service.consul"
zookeeper_client_port: "2181"
mesos_zookeeper_masters: "zk://{{ zookeeper_dns }}:{{ zookeeper_client_port }}/mesos"
mesos_owner: root
mesos_group: root

# Containerizer
mesos_containerizers: "docker,mesos"
mesos_executor_timeout: "5mins"

# Modules

mesos_slave_modules_file: "/etc/mesos-slave-modules.json"
mesos_logrotate_size: "1GB"
mesos_logrotate_options: "rotate 3"

mesos_docker_config_file: "/etc/docker/config.json"

# If 'true' cleans symlink 'meta/slaves/latest' to avoid mesos-slave restart failures on config changes
mesos_agent_meta_cleanup: true
mesos_agent_remove_tasks: true

mesos_option_prefix: "MESOS_"

# Additional configurations
mesos_additional_configs: []


# Additional configurations for master
mesos_master_additional_configs:
  - name: AGENT_PING_TIMEOUT
    value: "10secs"
  - name: MAX_AGENT_PING_TIMEOUTS
    value: "3"


# Additional configurations for slave
mesos_slave_additional_configs:
  - name: ATTRIBUTES
    value: "node_id:{{ ec2_tag_Name }}"
  - name: RESOURCES
    value: "ports(*):[4000-7999, 9000-32000]"
  - name: ISOLATION
    value: "cgroups/cpu,cgroups/mem,docker/runtime,filesystem/linux"
  - name: IMAGE_PROVIDERS
    value: docker
  # - name: EXECUTOR_REGISTRATION_TIMEOUT
  #   value: "10mins"
  - name: ENABLE_FEATURES
    value: "task_killing"
  - name: RECOVERY_TIMEOUT
    value: "30secs"
  - name: MODULES
    value: "file://{{mesos_slave_modules_file}}"
  - name: DOCKER_CONFIG
    value: "file://{{mesos_docker_config_file}}"
  - name: CONTAINER_LOGGER
    value: "org_apache_mesos_LogrotateContainerLogger"
  - name: SWITCH_USER
    value: "false"


# LVM Storage
use_mesos_lvm: False
mesos_lvm_backed: "{% if use_mesos_lvm %}True{% else %}False{% endif %}"

# Possible values: overlay (default), devicemapper, btrfs (unsupported)
# Used with mesos-storage-setup
mesos_storage_driver: overlay2

## Settings for devicemapper thinprovider (mesos-storage-setup)
## These are not used for overlay on lvm
## Refer to commentaries in ../templates/mesos-storage-setup.conf.j2
## or `man lvcreate` for acceptable sizes, and their syntax
mesos_lvm_data_volume_size: 40G
mesos_lvm_data_volume_size_min: 2G

mesos_lvm_auto_extend_pool: yes

# Settings for Overlayfs/Btrfs
mesos_volume_name: mesos

# Just propagate same size that thinprovider use
mesos_volume_size: "{{ mesos_lvm_data_volume_size }}"
mesos_volume_mount: "{{ mesos_work_dir }}"
mesos_volume_device: "/dev/{{ volume_group_name }}/{{ mesos_volume_name }}"
mesos_volume_fs_type: "{% if mesos_storage_driver == 'btrfs' %}btrfs{% else %}xfs{% endif %}"
mesos_volume_fs_opts: "{% if mesos_volume_fs_type == 'xfs' %}-i size=512{% endif %}"
