---

- name: "Install crowdstrike"
  tags: ["crowdstrike"]
  when: enable_crowdstrike
  block:
    - name: Copy crowdstrike installer files
      copy:
        src: "{{ crowdstrike_yum_file }}"
        dest: "/opt/{{ crowdstrike_yum_file }}"

    - name: Install crowdstrike package
      yum:
        name: "/opt/{{ crowdstrike_yum_file }}"
        state: "present"
        disable_gpg_check: true

    - name: Setup crowdstrike settings
      command: /opt/CrowdStrike/falconctl -s -f --cid="{{ crowdstrike_settings_cid }}" --tags="{{ crowdstrike_settings_tags }}"

    - name: Enable crowdstrike service
      service: name=falcon-sensor state=started enabled=yes

    - name: Cleanup installer
      file: path="/opt/{{ crowdstrike_yum_file }}" state=absent
