# file: roles/install-pgbouncer/tasks/configure.yml

- name: "create pgbouncer.ini"
  template:
    src: pgbouncer.ini.j2
    dest: "{{ pgbouncer_ini }}"
    owner: "{{ pgbouncer_admin_user }}"
    group: "{{ pgbouncer_admin_group }}"
    mode: 0644
  notify:
    - restart pgbouncer
  tags:
    - pgbouncer_ini

- name: "create pgbouncer.log"
  file:
    state: touch
    dest: "{{ pgbouncer_logfile }}"
    owner: "{{ pgbouncer_admin_user }}"
    group: "{{ pgbouncer_admin_group }}"
    mode: 0644

- name: configure pgbouncer helper
  copy:
    src: pgbouncer-helper.service
    dest: "{{ pgbouncer_helper_systemd_unit }}"

- name: "start pgbouncer-helper"
  service: name=pgbouncer-helper enabled=yes

- name: "start pgbouncer"
  service: name=pgbouncer state=started enabled=yes
