---
# - name: Add mesosphere repo
#   yum: name={{ mesosphere_yum_repo }} state=present
#   tags:
#     - mesos

- name: install mesos packages
  become: yes
  yum:
    name: "{{mesos_rpm_url}}"
    state: present
  tags:
    - mesos

# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory
  tags:
    - mesos

- include: lvm.yml
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave") and use_mesos_lvm
  tags:
    - mesos

- include: mesos.yml
  tags:
    - mesos

- meta: flush_handlers
