kafka_connect_service_name: kafka-connect

kafka_connect_image: confluentinc/cp-kafka-connect
kafka_connect_version: 5.3.1

jvm_starting_heap_size: 1g
jvm_maximum_heap_size: 4g
jvm_heap_metaspace_size: 96m

kafka_broker_endpoint: "kafka.service.consul:9092"
schema_registry_endpoint: "http://agent.mesos.service.consul:8081"
