---
- name: install packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
    - NetworkManager
  tags:
    - dnsmasq
    - bootstrap

- name: collect nameservers
  become: yes
  shell: "cat /etc/resolv.conf | grep -i '^nameserver' | cut -d ' ' -f2"
  register: nameservers_output
  tags:
    - dnsmasq

- name: collect dns search list
  become: yes
  shell: "cat /etc/resolv.conf | grep -i '^search' | cut -d ' ' -f2- | tr ' ' '\n'"
  register: dns_search_list_output
  tags:
    - dnsmasq

- name: set nameservers
  set_fact:
    nameservers: "{{ nameservers_output.stdout_lines }}"
  tags:
    - dnsmasq

- name: set dns search list
  set_fact:
    domain_search_list: "{{ dns_search_list_output.stdout_lines }}"
  tags:
    - dnsmasq

- name: ensure dnsmasq.d directory exists
  become: yes
  file:
    path: /etc/NetworkManager/dnsmasq.d
    state: directory
  tags:
    - dnsmasq

- name: configure dnsmasq for consul
  become: yes
  template:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul
    mode: 0755
  when: consul_conf_datacenter is defined
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: enable dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags:
    - dnsmasq

- name: configure networkmanager for dnsmasq
  become: yes
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    line: "dns=none"
    insertafter: "^\\[main\\]$"
  notify:
    - restart networkmanager
  tags:
    - dnsmasq

- name: List network-scripts which need fixup
  become: yes
  shell: "find /etc/sysconfig/network-scripts -name 'ifcfg-*'"
  register: list_of_network_scripts
  tags:
    - dnsmasq

- name: fixing PEERDNS in network-scripts
  become: yes
  lineinfile:
    dest: "{{ item }}"
    line: "PEERDNS=no"
    regexp: ^PEERDNS=.*'
  with_items: "{{list_of_network_scripts.stdout_lines}}"
  notify:
    - restart networkmanager
  tags:
    - dnsmasq

- name: add dnsmasq to /etc/resolv.conf
  become: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  tags:
    - dnsmasq

- meta: flush_handlers
