---
- hosts: tag_Service_resource
  tasks:
    - name: remove node from consul
      become: yes
      command: consul leave
      ignore_errors: yes

    - name: release all mesos tasks
      become: yes
      command: pkill -USR1 mesos-slave
      ignore_errors: yes

    - name: stop and disable mesos-slave
      become: yes
      service:
        name: mesos-slave
        state: stopped
        enabled: no
      ignore_errors: yes

- hosts: tag_Service_controller
  tasks:
    - name: remove node from consul
      command: consul leave
      ignore_errors: yes

    - name: stop and disable marathon
      become: yes
      service:
        name: marathon
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: stop and disable mesos
      become: yes
      service:
        name: mesos-master
        state: stopped
        enabled: no
      ignore_errors: yes
