---
# setup common configuation first.
- include: cluster/users.yml
- include: cluster/common.yml

# establish kafka cluster used for messaging, including logging.
- include: cluster/kafka-zk.yml
- include: cluster/kafka.yml
- include: cluster/kafka-connect.yml
- include: cluster/kafka-connect-lsql.yml

# setup mesos/marathon cluster.
- include: cluster/controller.yml
- include: cluster/resource.yml
- include: cluster/edge.yml

# setup vpn access
- include: cluster/vpn.yml

# setup logging and monitoring.
- include: monitoring/logging.yml
- include: monitoring/netdata.yml
- include: monitoring/zabbix.yml
