---
chronos_version: 2.5.0
mesosphere_yum_repo: "https://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-2.noarch.rpm"

chronos_yum_package_name: "chronos-{{ chronos_version }}"

# # == chronos conf ==
chronos_conf_path: /etc/chronos/conf
chronos_sysconfig_path: /etc/sysconfig/chronos
chronos_systemd_unit: /usr/lib/systemd/system/chronos.service

# Control whether systemd service unit requires mesos-master service unit.
chronos_systemd_require_mesos: yes

# List of command or script that must be run before service unit is started.
chronos_systemd_unit_startpre:
  - "/usr/local/bin/zookeeper-wait-for-listen.sh {{ chronos_zk_dns }}"

mesos_zk_chroot: "mesos"
chronos_zk_auth: ""
chronos_zk_dns: "zookeeper.service.consul"
chronos_zk_port: 2181
chronos_zk_chroot: chronos
chronos_zk_connect: "zk://{{ chronos_zk_dns }}:{{ chronos_zk_port }}/{{chronos_zk_chroot}}"
chronos_zk_mesos_master: "zk://{{ chronos_zk_dns }}:{{ chronos_zk_port }}/{{ mesos_zk_chroot }}"

chronos_hostname: "{{ ec2_tag_Name }}.node.dc1.consul"
chronos_bind_address: "{{ ansible_default_ipv4.address }}"
chronos_port: 4400

# Dictionary of configuration options for Chronos
chronos_conf_options:
  zk_hosts: "{{ chronos_zk_connect }}"
  master: "{{ chronos_zk_mesos_master }}"
  hostname: "{{ chronos_hostname }}"
  http_port: "{{ chronos_port }}"
  #mem_opts: "{{ chronos_env_java_opts }}"
  mesos_framework_name: "chronos"

# TODO chronos_env_java_opts: "-Xmx512m"
chronos_sysconfig_vars:
  LIBPROCESS_IP: "{{ chronos_bind_address }}"
