---
- name: Add mesosphere repo
  yum: name={{ mesosphere_yum_repo }} state=present

- name: Install Marathon
  yum: name={{ marathon_yum_package }} state=present
  notify: Restart marathon

- include: conf.yml
  tags:
    - marathon

- name: Enable Marathon service
  service: name=marathon enabled=yes state=started

- name: generate marathon consul service
  template:
    src: marathon-consul.j2
    dest: "{{ consul_dir }}/marathon.json"
  notify:
    - reload consul
  tags: ["consul"]

- meta: flush_handlers

- name: wait for marathon service to be registered
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: "{{ marathon_port }}"
    delay: 10
    timeout: 300
    state: present

# - include: jobs.yml
